[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  targetPort = 5173
  autoLaunch = true

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NPM_VERSION = ""
  YARN_VERSION = ""
  YARN_FLAGS = ""
  NODE_ENV = "production"
