[build]
  command = "npm run netlify-build"
  publish = "dist"
  functions = "functions"
  
  # Configuración de variables de entorno para la construcción
  [build.environment]
    NODE_VERSION = "20"
    NPM_FLAGS = "--legacy-peer-deps"
    NPM_VERSION = ""
    YARN_VERSION = ""
    YARN_FLAGS = ""
    NODE_ENV = "production"
    VITE_APP_ENV = "production"
    
    # Configuración de redirecciones para SPA
    [[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200

# Configuración para el entorno de producción
[context.production]
  command = "npm ci && npm install && npm run build"

# Configuración para previsualización de despliegues
[context.deploy-preview]
  command = "npm ci && npm install && npm run build"

# Configuración para despliegues de ramas
[context.branch-deploy]
  command = "npm ci && npm install && npm run build"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  targetPort = 5173
  autoLaunch = true

# Configuración de encabezados de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googleapis.com https://*.firebaseio.com https://*.firebase.com; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com https://*.firebase.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
