[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de funciones (si usas serverless functions)
[functions]
  node_bundler = "esbuild"

# Configuración de desarrollo local
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  framework = "vite"
