[build]
  command = "npm ci && npm install && npm run build"
  publish = "dist"
  functions = "functions"

# Configuración para el entorno de producción
[context.production]
  command = "npm ci && npm install && npm run build"

# Configuración para previsualización de despliegues
[context.deploy-preview]
  command = "npm ci && npm install && npm run build"

# Configuración para despliegues de ramas
[context.branch-deploy]
  command = "npm ci && npm install && npm run build"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  targetPort = 5173
  autoLaunch = true

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_VERSION = ""
  YARN_VERSION = ""
  YARN_FLAGS = ""
  NODE_ENV = "production"
  VITE_APP_ENV = "production"

# Configuración de encabezados de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
